# Generated by Django 4.2.1 on 2023-11-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_department_dep_id_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_des',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
